### ISSUE TITLE
Avoir la liste des skillz avec leur catégories

### ISSUE THREAD

**Issue by esciara** [xebia-france/xskillz-v2#12]
Se serait pratique d'avoir une page qui permet de voir toutes les skillz organisées dans leur catégories. Ca permettrait d'avoir des idées.  Em

**Comment by cheubes** [comment]
Il pourrait également être intéressant de visualiser (par catégories ou non) les tops (et éventuellement) les flops :
 - Les skills qui intéresse le plus / le moins de Xebians.
 - Les skills réunissant le plus / le moins d'étoiles.
 - Les skills les plus / les moins présentes.
 - ...
