### ISSUE TITLE
Impossible de charger la page d'un utilisateur

### ISSUE THREAD

**Issue by slequeux** [xebia-france/xskillz-v2#29]
Lorsque je tente de charger la page de Loïc Divad, l'éran de chargement reste en boucle. Dans la console, je vois apparaître un 404.

Le problème serait-il lié à l'accent sur le i ?

**Comment by slequeux** [comment]
C'est en effet cela, si je change le ï en i dans l'url, la page se charge correctement

**Comment by jsmadja** [comment]
C'est corrigé mais pas déployé encore.

Le jeu. 3 nov. 2016 18:34, Sylvain Lequeux <notifications@github.com> a
écrit :
