### ISSUE TITLE
profile picture

### ISSUE THREAD

**Issue by giulbia** [xebia-france/xskillz-v2#30]
Hello,

Je ne peux pas changer l'image par défaut pour mettre ma photo.

**Comment by giulbia** [comment]
J'ai découverts que ça se fait à travers gravatar.

**Comment by jsmadja** [comment]
Du coup, que souhaites-tu faire avec ton issue ?

**Comment by giulbia** [comment]
On peut le fermer au moins que tu aies envie d'ajouter la fonctionnalité directement dans skills, non ?

**Comment by jsmadja** [comment]
On peut laisser ouvert.

**Comment by jsmadja** [comment]
Won't do.
