### ISSUE TITLE
adresse mail inexistant ?

### ISSUE THREAD

**Issue by giulbia** [xebia-france/xskillz-v2#31]
Delivery to the following recipient failed permanently:

     skillz@xebia.fr

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain xebia.fr by aspmx.l.google.com. [2607:f8b0:4001:c05::1b].

The error that the other server returned was:
550-5.1.1 The email account that you tried to reach does not exist. Please try
550-5.1.1 double-checking the recipient's email address for typos or
550-5.1.1 unnecessary spaces. Learn more at
550 5.1.1  https://support.google.com/mail/?p=NoSuchUser 73si19214231ios.119 - gsmtp

**Comment by jsmadja** [comment]
Address created.
