### ISSUE TITLE
Accentuation et profils

### ISSUE THREAD

**Issue by blacroix** [xebia-france/xskillz-v2#32]
*En tant que* utilisateur connecté
*Si* je suis dans la page *Utilisateurs*
*Si* je clique sur Michaël Ohayon
*Alors* je souhaite voir son profil
*Actuel* j'ai une page blanche à cause de l'accentuation dans l'URL

**Comment by jsmadja** [comment]
Je déploie la new version tout à l heure

Le jeu. 10 nov. 2016 15:46, Benjamin LACROIX <notifications@github.com> a
écrit :
