### ISSUE TITLE
Offrir aux administrateurs la possibilité de supprimer un utilisateur

### ISSUE THREAD

**Issue by cheubes** [xebia-france/xskillz-v2#38]
Préférence > Utilisateurs : Offrir la possibilité de supprimer un utilisateur.
Plutôt une suppression logique (date de sortie) ?

**Comment by tcavin** [comment]
+1

**Comment by jsmadja** [comment]
Il faut saisir la date de départ du Xebian.

Avant cette date il sera toujours visible dans les listes de sélection, ensuite il ne sera plus visible.
