### ISSUE TITLE
Ajouter la notion d’ancienneté chez Xebia

### ISSUE THREAD

**Issue by cheubes** [xebia-france/xskillz-v2#39]
Préférence > Utilisateurs : Ajouter une fonctionnalité "Définir la date d’entrée chez Xebia".
Profil utilisateur : Afficher l’ancienneté chez Xebia.

**Comment by jsmadja** [comment]
En tant que manageur
Je souhaite pouvoir définir la date d'embauche d'un utilisateur
Afin de la voir apparaitre sur son profil
