### ISSUE TITLE
Ajout d'une compétence vide

### ISSUE THREAD

**Issue by agoncal** [xebia-france/xskillz-v2#50]
Lorsqu'on ne saisit aucune compétence et qu'on clique sur "Ajouter", il y a le message "compétence ajoutée" qui s'affiche en bas de la page. Il faudrait avoir le bouton "ajouter" disable si la compétence est vide, ou avertir l'utilisateur qu'il n'a pas saisit de compétence

**Comment by thomascarvalho** [comment]
C'est fixé avec la PR #66
