### ISSUE TITLE
Possibilité de marquer une compétence négative

### ISSUE THREAD

**Issue by MichaelBitard** [xebia-france/xskillz-v2#52]
Parce qu'on adore détester des trucs, il manque le fait de pouvoir marquer une compétence qu'on n'aime pas.

Exemple : 
Imaginons qu'après avoir fait du PHP, je pense être compétent dessus mais que je ne veuille plus jamais en faire, la seule solution c'est de ne pas marquer que ça fait partie de mes compétences.

**Comment by jsmadja** [comment]
Quel est le problème de ne pas mettre PHP dans son profil pour ce cas là ?

**Comment by MichaelBitard** [comment]
Potentiellement il n'y a pas de problème, sauf si on te propose une mission
qui contient à la fois des technos sur lesquelles tu as envie de bosser et
certaines que tu blacklistes, si tu ne marques pas la compétence comme
"blacklistée" tu ne le verras pas apparaitre et potentiellement tu pourrais
partir sur une mission moins intéressante parce que tu n'as pas pu mettre
une information significative dans l'outil.

Je sais pas si c'est clair :)

**Comment by jsmadja** [comment]
Je pense que c'est donné trop d'importance à l'outil et oublier que les choix se feront aussi via une discussion orale/écrite d'humain à humain.

**Comment by MichaelBitard** [comment]
Oui c'est sûr, je ne voyais pas l'outil comme autre chose que ça, je
pensais que ça permettrait juste d'étoffer l'outil, n'hésitez pas à clore
l'issue.

**Comment by jsmadja** [comment]
Ok je clôture. Mais la discussion était intéressante. N'hésite pas à relancer des discussions dans les issues.
Merci.
