### ISSUE TITLE
L'affectation à un manageur de fonctionne plus

### ISSUE THREAD

**Issue by cheubes** [xebia-france/xskillz-v2#57]
Sur https://skillz.xebia.fr/management, je repère un équipier sans manageur dans la dernière liste (ex : Qian).

Sur https://skillz.xebia.fr/settings, j'affecte cet équipier à son manageur (ex : Qian > Benjamin)

Je retourne sur https://skillz.xebia.fr/management / Cmd Shift R / l'équipier n'a toujours pas de manageur.

**Comment by cheubes** [comment]
Il s'agit peut être d'un problème de doublon.
Après vérification : 
- Qian est dans la liste de Benjamin et dans la liste des sans manageurs.
- Arnaud est dans la liste de Benjamin et dans la liste des sans manageurs.
- Tomas est dans la liste de Thomas et dans la liste des sans manageurs.
- ...

**Comment by jsmadja** [comment]
Ok, ca sent la jointure SQL pourrie

**Comment by jsmadja** [comment]
Les profils étaient en double
