### ISSUE TITLE
Formulaire profil

### ISSUE THREAD

**Issue by blacroix** [xebia-france/xskillz-v2#6]
_En tant que_ utilisateur connecté
_Si_ je suis sur mon profil
_Alors_ je peux ajouter mon téléphone
_Alors_ je peux ajouter mon email

**Comment by cheubes** [comment]
Cela permettrait de remplacer la page annuaire du wiki.

**Comment by blacroix** [comment]
Formulaire d'ajout de téléphone terminé. RAF ajout du téléphone sur la fiche du Xebian.
