### ISSUE TITLE
Impossible d'afficher la fiche d'Alexis Chotard

### ISSUE THREAD

**Issue by jsmadja** [xebia-france/xskillz-v2#62]
https://skillz.xebia.fr/user/alexis-chotard

bundle.js:28Uncaught (in promise) TypeError: Cannot read property 'color' of undefined(…)

**Comment by slequeux** [comment]
J'ai le même souci avec la fiche de Zahir Hamroune

https://skillz.xebia.fr/user/zahir-hamroune
