### ISSUE TITLE
Le merge de compétences ne fonctionne pas

### ISSUE THREAD

**Issue by joe-mojo** [xebia-france/xskillz-v2#81]
J’essaie de remplacer “maven” par “Maven” car “Maven” est bien dans “devops” alors que “maven” est sans catégorie

La requête est un PUT sur /skills (déjà pas bon) avec un body `{"from":null, "to":null}` (normal ???) 

J’ai essayé de rejouer la requêmte avec la console FF en modifiant juste le body : `{"from": "maven", "to":"Maven" }` => là j’ai une 500 qui leak des infos sur la DB : "ER_BAD_FIELD_ERROR: Unknown column 'maven' in 'where clause’"

**Comment by jsmadja** [comment]
Je viens de tester en prod, pas eu de problème.

@joe-mojo Tu ferais quoi à la place du PUT /skills ?

**Comment by joe-mojo** [comment]
Je ferais un POST /skills/merge (ressource dédiée en tant que handler pour le merge) avec en body le `{"from": "ancienneSkill", "to": "nouvelleSkill"}`
On pourrait faire un PUT sur la nouvelle skill pour la mettre à  jour complètement et un DELETE sur l'anciennce, mais ce n'est pas atomique. 

Autre solution, dire qu'une ressource skill particulière est capable de se merger toute seule avec une autre => ça donnerait POST /skills/nouvelleSkill?merge=ancienneSkill
(j'aime moins à cause de l'effet de bord créé par une ressource non-dédiée à ça)

**Comment by jsmadja** [comment]
J aime la v1
