### ISSUE TITLE
Rajouter le type de mission souhaité

### ISSUE THREAD

**Issue by agoncal** [xebia-france/xskillz-v2#86]
Pour AllCraft on peut avoir des profils d'indep interessés plutot par des missions d'expertise, de courte durée. Ca pourrait être pas mal de rajouter dans le profile (genre, liste box) : 

Mission souhaitée :
* Mission longue (6-12 mois) à temps plein
* Mission moyenne (3-6 mois) à temps plein
* Mission courte (< 3 mois) à temps plein
* Mission à mi-temps
* Mission d'expertise de qques jours

**Comment by jsmadja** [comment]
Won't do.
